Pass `--accept-flake-config` only during flake-related commands (#361)
`--accept-flake-config` expects the flake to be already enabled, which
will fail `om health` on systems with flake not enabled.

## Error

```
❄️  nix --accept-flake-config --version️
Error: Unable to gather nix info

Caused by:
    0: Nix command error: Command error: Process exited unsuccessfully. exit_code=Some(1) stderr=error: experimental Nix feature 'flakes' is disabled; add '--extra-experimental-features flakes' to enable it

    1: Command error: Process exited unsuccessfully. exit_code=Some(1) stderr=error: experimental Nix feature 'flakes' is disabled; add '--extra-experimental-features flakes' to enable it

    2: Process exited unsuccessfully. exit_code=Some(1) stderr=error: experimental Nix feature 'flakes' is disabled; add '--extra-experimental-features flakes' to enable it
```

---------

Co-authored-by: Sridhar Ratnakumar <srid@srid.ca>