fix: failure to parse Lix version
```
direnv: using omnix
Invoking omnix using: nix --accept-flake-config --option builders '' -j0 run github:juspay/omnix --
⌨️  Preparing to develop project: .
❄️  nix --version️
Error: Unable to gather nix info

Caused by:
    0: Nix command error: Failed to decode command stdout (from_str error): Failed to parse string: Parse error (int): `nix --version` cannot be parsed
    1: Failed to decode command stdout (from_str error): Failed to parse string: Parse error (int): `nix --version` cannot be parsed
    2: Failed to parse string: Parse error (int): `nix --version` cannot be parsed
```